/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/edit-profile-modal` | `/edit-profile-modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-post` | `/add-post`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-profile` | `/my-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/services/auth.service`; params?: Router.UnknownInputParams; } | { pathname: `/services/post.service`; params?: Router.UnknownInputParams; } | { pathname: `/services/storage.service`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/auth.context`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/edit-profile-modal` | `/edit-profile-modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add-post` | `/add-post`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-profile` | `/my-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/services/auth.service`; params?: Router.UnknownOutputParams; } | { pathname: `/services/post.service`; params?: Router.UnknownOutputParams; } | { pathname: `/services/storage.service`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/auth.context`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/edit-profile-modal${`?${string}` | `#${string}` | ''}` | `/edit-profile-modal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add-post${`?${string}` | `#${string}` | ''}` | `/add-post${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-profile${`?${string}` | `#${string}` | ''}` | `/my-profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/services/auth.service${`?${string}` | `#${string}` | ''}` | `/services/post.service${`?${string}` | `#${string}` | ''}` | `/services/storage.service${`?${string}` | `#${string}` | ''}` | `/contexts/auth.context${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/edit-profile-modal` | `/edit-profile-modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-post` | `/add-post`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-profile` | `/my-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/services/auth.service`; params?: Router.UnknownInputParams; } | { pathname: `/services/post.service`; params?: Router.UnknownInputParams; } | { pathname: `/services/storage.service`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/auth.context`; params?: Router.UnknownInputParams; };
    }
  }
}
